### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by itsmecodyp** [itsmecodyp/WorldBox#3]
Main priorities:
- [ ] Make and move config stuff to Settings menu
- [ ] Load conversation starter and responses from .json files
- [ ] Update/rewrite kingdom merge
- [ ] Add, reference and extend BodySnatchers
- [ ] Finish enabling AssetModLoader

WorldBox3D:
- [ ] Fix tile3d
- [ ] Remake building thickening

Finish cultist system:
- [ ] "God" name generator
- [ ] A few more "preach" lines
- [ ] More responses, general crowd chatter
